theme = "lynx"
title = "Atletiekregels.nl"

languageCode = "nl"
defaultContentLanguage = "nl"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Atletiekregels.nl"
  headline = "Een linkpagina met links naar reglementen"
  image = ""
  links = [
    { link = { href = "au/", text = "Atletiekunie", target = "_self", icon = "atletiekunie-oranje" } },
    { link = { href = "wa/", text = "World Athletics", target = "_self", icon = "world-athletics" } },
    { link = { href = "wpa/", text = "World Para Athletics", target = "_self", icon = "world-para-athletics" } },
    { link = { href = "wma/", text = "World Master Athletics", target = "_self", icon = "world-master-athletics" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
