name: Hugo Deploy

on:
  workflow_dispatch: 
  push:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tfapply:
    uses: durandguru/shared-workflows/.github/workflows/hugo-deply-nginx-docker.yml@main
    secrets:
        WG_CLIENT_PRIVATEKEY: ${{ secrets.WG_CLIENT_PRIVATEKEY}}
        SSH_KEY: ${{ secrets.SSH_KEY}}